# environment.yml
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - coverage
  - cryptography
  - dvc
  - gymnasium-box2d
  - huggingface_hub
  - ipykernel
  - ipywidgets
  - joblib
  - matplotlib
  - pandas
  - pip
  - pytest
  - pytest-check
  - python >= 3.11
  - python-dotenv
  - pytorch >= 2.0.0
  - pytorch-cuda >= 12.*
  - stable-baselines3
  - swig