# enviornment.yml
name: r2seedo-default
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - coverage
  - gymnasium-box2d
  - ipykernel
  - ipywidgets
  - matplotlib
  - pandas
  - pip
  - pytest
  - pytest-check
  - python >= 3.11
  - pytorch >= 2.0.0
  - pytorch-cuda >= 12.*
  - stable-baselines3
  - swig
  - pip:
    - huggingface-sb3
platforms:
  - linux-64